### ISSUE TITLE
plugin to construct r231 gives you a white screen

### ISSUE THREAD

**Issue by ibiz3091** [el3um4s/construct-plugins-and-addons#6]
Good afternoon, unfortunately adding your plugin to construct r231 gives you a white screen. Will there be an update to your amazing plugin?

**Comment by el3um4s** [comment]
Hi.

Many of my plugins can be implemented directly in JavaScript inside construct 3. I think it's a better solution, especially after C3 allows modules to be used.

Anyway, which plugin is giving you trouble?

**Comment by ibiz3091** [comment]
I apologize that I did not specify the plugin. This is an htmlelement. I use it to create a mobile app. In r225, it works properly.

**Comment by el3um4s** [comment]
Ok, thanks.

I think there is a problem with the new _scripting support for JavaScript Modules_ introduced with the beta [r226](https://www.construct.net/en/make-games/releases/beta/r226).

Try setting:
- Use worker: **NO**
- Scripts Type: **CLASSIC**

![image](https://user-images.githubusercontent.com/23579630/104610356-5237ea00-5684-11eb-814a-f2edc7fa30d2.png)

**Comment by ibiz3091** [comment]
Yes, it worked. Thank you so much for your help.

**Comment by ibiz3091** [comment]
Yes, it worked. Thank you so much for your help.
