### ISSUE TITLE
Drag & Drop - Align text to bottom

### ISSUE THREAD

**Issue by iYonga** [el3um4s/construct-plugins-and-addons#7]
How to align the text to the bottom? CSS code I tried didn't work. Great plugin though! Thanks so much!

**Comment by el3um4s** [comment]
You can do this with Flexbox `align-item: flex-end` ([Basic concepts of flexbox](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox))

```
#myelement {
 display: flex;
 justify-content: center;
 align-items: flex-end;
}
```

![image](https://user-images.githubusercontent.com/23579630/107612931-9dbfc280-6c47-11eb-98b7-1e8cd5068699.png)

![image](https://user-images.githubusercontent.com/23579630/107612975-b16b2900-6c47-11eb-8451-4d4e67b9917b.png)

**Comment by iYonga** [comment]
Thank you!
