### ISSUE TITLE
Drag & Drop - Putting sprites on it.

### ISSUE THREAD

**Issue by iYonga** [el3um4s/construct-plugins-and-addons#8]
I want to put an upload icon sprite on the Drag & Drop pane. Is that possible? All text and sprites I put seem to go behind the object. 

Edit: It would also help to make the object transparent instead (not the borders)

**Comment by el3um4s** [comment]
You can change the backgroud color via CSS:  `backround-color: transparent;`

![image](https://user-images.githubusercontent.com/23579630/107644950-674e6b80-6c78-11eb-98fb-319315fb0a45.png)

![image](https://user-images.githubusercontent.com/23579630/107645240-c1e7c780-6c78-11eb-8070-8556c7c709ad.png)


About your question see this: [CONSTRUCT 3 DOCS](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/button)

> Form controls are actual HTML elements floating above the game canvas. Therefore, nothing can be displayed on top of a form control, apart from other form controls. Form controls position themselves according to the layer parallax, scale and so on. However they are not truly "in the game" (since they float above), so it is recommended to avoid using scrolling, parallax and layer scaling with form controls, otherwise the end result can feel unnatural.

**Comment by iYonga** [comment]
Yeah, I figured it was an HTML element. Figured it out.
